name: daily-loader
on:
  schedule:
    - cron: "30 9 * * *"  # 05:30 est daily; 
  workflow_dispatch:      
jobs:
  run-loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run daily job
        env:
          DB_URI: ${{ secrets.DB_URI }}
        run: |
          . .venv/bin/activate
          python scripts/pipeline.py
